### ISSUE TITLE
Unreachable code block for paused files

### ISSUE THREAD

**Issue by zeeMonkeez** [BlackrockMicrosystems/NPMK#11]
The [`if` block testing for paused files in `openNSx`, currently L515](https://github.com/BlackrockMicrosystems/NPMK/blob/master/NPMK/openNSx.m#L515) cannot be reached, because `NSx.RawData.PausedFile` is set only ever non-zero [later](https://github.com/BlackrockMicrosystems/NPMK/blob/master/NPMK/openNSx.m#L598).

Also it seems code for reading beginnings and ends of data segments occurs twice:
https://github.com/BlackrockMicrosystems/NPMK/blob/master/NPMK/openNSx.m#L573
https://github.com/BlackrockMicrosystems/NPMK/blob/master/NPMK/openNSx.m#L622

**Comment by kianabc** [comment]
Hi Jonas, the L# didn't correspond to what you were referring to. Is it because the code has changed? I only saw your message now.

**Comment by zeeMonkeez** [comment]
The corresponding piece of code has moved down about ten lines (`if NSx.RawData.PausedFile == 1`)

**Comment by kianabc** [comment]
I see. Thanks. Fixed. Will push soon.
