### ISSUE TITLE
Paused ns1 files have non-empty extraneous data segments

### ISSUE THREAD

**Issue by zeeMonkeez** [BlackrockMicrosystems/NPMK#12]
Tested with Central 6.05.02: Record a file with sample group 1 data, including pauses. The resulting `ns1` will contain extraneous data segments of *length 1*, starting at the same timestamp as the following data section. [There is code](https://github.com/BlackrockMicrosystems/NPMK/blob/master/NPMK/openNSx.m#L829) removing extraneous *empty* sections, but they only seem to occur in `.ns2`-`.ns6` files at pauses.
As a result, the data segments of simultaneously recorded `.nsx` files will not match up.
This should probably also lead to a bug report for Central?

**Comment by NHalper** [comment]
Jonas, this definitely appears to be a Central bug. I know that a bug related to segments that appeared between pauses was fixed moving into 6.05.03, so you may want to update to 6.05.04 to see if this bug persists.

**Comment by zeeMonkeez** [comment]
@NHalper I didn't know there have been updates – just saw them on the website.

Would there be cases where we'd expect two data segments to have the same timestamp, and the first one to have one sample? If not, maybe the above linked fix should be extended to include these NS1 files?

**Comment by NHalper** [comment]
That is the approximate behavior of the bug that should be fixed in the newest version of Central. It was an artifact of a new method we implemented to better capture and describe any packet loss that a user experiences. Overall, nobody should experience any packet loss, but the update put a much better failsafe in place. In the process though, we created some annoying data segments for users that simply pause the data for trials or other reasons.

**Comment by zeeMonkeez** [comment]
Oh I meant would there be legitimate reasons for data segments with 1 sample?

Just to make sure that by deleting these segments no valid data gets deleted when using `openNSx`.

**Comment by NHalper** [comment]
Jonas,

Our understanding is that these segments that appear to occur in a period of 0 timestamps (timestamp doesn’t change between this segment and the next) do not have legitimate data in them.

Nick

**Comment by kianabc** [comment]
Can I close this since it's not related to NPMK?

**Comment by zeeMonkeez** [comment]
They're related in that `openNSx` ought to open these files correctly (i.e. without spurious blocks)

**Comment by kianabc** [comment]
Do you happen to have a data file that this bug affects it? It'd be great if you could share it. I just don't see how NS2-6 are fixed, but NS1 is not. 

K
