### ISSUE TITLE
openNSxHL

### ISSUE THREAD

**Issue by czawora** [BlackrockMicrosystems/NPMK#20]
why does line 111 of openNSxHL create a zero padding vector of 2 times the number of time points * channels? Would not one time point per channel be correct for this padding?

`paddedZeros = zeros(numofChannels * begTimestamp * 2, 1);`

**Comment by kianabc** [comment]
I honestly don't remember. Is it causing an issue for you? If yes, I can look into it.

**Comment by kianabc** [comment]
Sorry I just saw this--2 years later. :(

**Comment by kianabc** [comment]
Since I haven't heard from you, I'm going to close this ticket now. Let me know if this problem persists. 

Kian
