### ISSUE TITLE
Issue with opening NS6 file 

### ISSUE THREAD

**Issue by skjenks** [BlackrockMicrosystems/NPMK#24]
Hello, 
I am having an issue with loading my NS6 file (taken from blackrock). When I run this file (128 channels and 40,116,762 KB) it says that it is out of memory. Loading a smaller NS6 file works. 

The problems is when I try to only load two samples of one channel (in the big file) the error still appears. 
1) Does anyone know how I can go about fixing this problem so I can eventually analyze all of the data? 

2) Also, do you think opening the file channel by channel would help? if so how? 

Thank you!

**Comment by kianabc** [comment]
Hi,

Please contact Blackrock support at support@blackrockmicro.com.

Best,
Kian

**Comment by skjenks** [comment]
@kianabc 
Thank you, I will do that.
