### ISSUE TITLE
License of NPMK

### ISSUE THREAD

**Issue by morales-gregorio** [BlackrockMicrosystems/NPMK#26]
Dear developers,

We have used your software package to preprocess some .ns6 and .nev files, that will be provided in our next publication.

We were wondering what is the licensing of your software package, since no license file is provided in the repository. In particular we would like to know:
- Should we cite you if we have used your software?
- Can we provide a copy of your code in our publication repository? (we would like to do this for reproducibility, in case your functions eventually change and are no longer compatible with our workflow)

Thanks in advance,
Aitor Morales-Gregorio

**Comment by NHalper** [comment]
Aitor,

Yes, please do cite Blackrock Microsystems since we are the sole contributors to the Github project.

You can provide a copy of the code in your publication repository; I think this is a good idea.

Nick

**Comment by morales-gregorio** [comment]
Since the license file was included all doubts are clear now! Thanks!
