### ISSUE TITLE
openNSx misleading default units for data

### ISSUE THREAD

**Issue by morales-gregorio** [BlackrockMicrosystems/NPMK#28]
Hey there!

I was loading some data into what I thought was 'uV' units because when I checked the `NS6.ElectrodeInfo.AnalogUnits` it said that the units are 'uV'.

I was later surprised to find that I would need to pass a parameter to the function in order to make it into actual 'uV' units. Additionally, the documentation for this parameter is a bit misleading.
```
%   'uV':         Will read the recording waveforms in unit of uV instead of
%                 raw values. Note that this conversion may lead to loss of
%                 information (e.g. 15/4 = 4) since the data type will
%                 stay in int16. It's recommended to read raw spike
%                 waveforms and then perform the conversion at a later
%                 time.
%                 DEFAULT: will read recording information in raw.
```

Also, the loaded data is indeed given as `double` and not as `int16` when using this parameter on my .ns6 files. This functionality or the documentation would have to be adjusted.

To avoid people from wrongfully interpreting the 'raw' signals as if they were the analog signals, I would suggest doing one of the following:
1. Make the default to return the data in 'uV', even if it takes more space in memory.
-- or --
2. Make the units when loading without 'uV' something else, since they are not the real units of the currently loaded data.

I hope this helps make NPMK a bit more user friendly.
Let me know what you think and if you think there is a better way of avoiding possible confusion when loading data with NPMK.

Best,
Aitor

**Comment by ferchaure** [comment]
Hi, sorry to involve me in the issue but option 1 will break a lot of code and (because the raw data will use 4 times the usual memory) it will create a few memory-related issues in long recordings.
Nevertheless, I understand Aitor's suggestion. I always check that comment before reading some file using npmk because is not clear in the data, for that reason I think that option 2 is a good idea.

**Comment by morales-gregorio** [comment]
Thanks @ferchaure for sharing your ideas on this! I had not thought on the broad implications of option 1 indeed, not looking forward to break anything hehe.

I think that in general a better documentation would already help avoid this issue, like a proper distinction between raw and actual analogsignals in the docstring of the openNSx function for example. Also the option could be named something else than 'uV' to make it more intuitive. 

Best,
Aitor

**Comment by kianabc** [comment]
Added this as a warning to NPMK. It will prompt the user and will ask if the user wants to continue to see this warning every time. 

The uV vs. 1/4 uV is in the file spec. It's not something I can change.

Kian

**Comment by kianabc** [comment]
Never mind. 6 minutes later and I also implemented the AnalogUnits to say 250 µV (raw). Happy now, Aitor? :) 

Kian
