### ISSUE TITLE
incorrect DateTime

### ISSUE THREAD

**Issue by vncntprvst** [BlackrockMicrosystems/NPMK#29]
Hi,
When loading files with openNSx, the `DateTime` field in `NSx.MetaTags` is incorrect. 
The error seem to originate here: 
https://github.com/BlackrockMicrosystems/NPMK/blob/84e7e1d9409c9d0d796cd71188f1ac29ba81db9e/NPMK/openNSx.m#L491
For example, this returns a datetime as follow:  **25-Aug-2020 22:21:50**, while executing
 ```
t                          = dir(fileFullPath);
NSx.MetaTags.DateTime      = t.date;
```
returns **25-Aug-2020 18:22:39**, which is the correct datetime.
Could you take a look at this?
Thanks

**Comment by kianabc** [comment]
This is actually how the file format is written. One time is in UTC and another in local time. I don't know why it was written this way, but that's how it was coded. Maybe one day it will be fixed in Central.

**Comment by kianabc** [comment]
Feel free to email Blackrock support at support@blackrockmicro.com for further information.

**Comment by vncntprvst** [comment]
Thanks for the explanation!
