### ISSUE TITLE
wrong AnalogUnits for analog inputs 

### ISSUE THREAD

**Issue by ferchaure** [BlackrockMicrosystems/NPMK#30]
Hi, the recent change in the units of the channels have issues for the analog input channels. Remember that the associated analog_unit, max_digital and max_analog (as called by cbmex) are different from the ones in the front end channels. 

The correct way to define the value in volts associated with the digital signal is **max_analog**/**max_digital**  in **analog_unit** units. That gives 0.25 **uV** for the front end and around 0.17 **mV** for the analog input.

Maybe the previous AnalogUnits field can be renamed as MaxAnalogUnits to be clear. And probably a new field that gives the conversion rate to uV or mV for each channel.

Cheers,
Fernando

**Comment by ferchaure** [comment]
Ki kian, the new version is better but it doesn't check the unit of MaxAnalogValue (some are in mV and others are in uV) 

Therefore some NSx.ElectrodesInfo(headerIDX).AnalogUnits, as you calculated, will be in uV (analog input of the nsp) and others in nV.

**Comment by kianabc** [comment]
Hi Fernando, I had actually resolved this last week. Your message reminded me to upload the new version. Can you give me a more specific example of what looks wrong? You said some are in mV and some are in nV.  Let me know exactly what is wrong. Thanks.

**Comment by ferchaure** [comment]
For example, Analog In channels have an Analog Range from -5000 to 5000 mV. The code assumes that the range is -5000 to 5000 uV  (never checks the units of the Analog Range).

**Comment by kianabc** [comment]
Thank you Fernando. I decided to completely redo this part of the code and
how it reads the units and resolution. I'm going to do some testing and
once that's done I will upload the latest version so you can look at it.
Thanks so much for your feedback. You should get a notification sometime
today hopefully.

**Comment by kianabc** [comment]
This has been fixed. Note the new variable under NSx.ElectrodesInfo(idx).Resolution. You should always multiple your data NSx.Data(idx,:) by NSx.ElectrodesInfo(idx).Resolution to get the correct µV value. I hope this helps. Thanks for your feedback and help to make NPMK read these values properly.

Best,
Kian
