### ISSUE TITLE
openNEV.m | Invalid Argument when passing string filename

### ISSUE THREAD

**Issue by sparkerBCI** [BlackrockMicrosystems/NPMK#33]
In [openNEV.m](https://github.com/BlackrockMicrosystems/NPMK/blob/master/NPMK/openNEV.m), line 288 gets the length of `temp` like it is an array of chars. Passing a string filename causes the `length()` function to return `1`, so the filename is not parsed, since `openNEV` needs a filename longer than 3 chars.

I ran into this issue initially using this minimal example:
`openNEV(strcat(folder_path, nev_filename))`

I recreated it in the Command Window using:
`openNEV("C:\complete\path\to\file.nev")`

In both cases, I saw the following output:
`"Invalid argument '"    "C:\Users\samue\Documents\Uni\Brow…"    "' ."`
and no `.mat` file was generated.

I found this issue using Release 2020a, using NPMK version 5.5.0.0 on Windows 10 Home 20H2

**Comment by kianabc** [comment]
Thanks Sam. I'll fix this shortly. Best, Kian

**Comment by sparkerBCI** [comment]
For your consideration, I have modified the two files I directly needed to use in [pull request 35](https://github.com/BlackrockMicrosystems/NPMK/pull/35).

All the best, 
Sam

**Comment by kianabc** [comment]
thank you!
