### ISSUE TITLE
openNsx.m throwing error with .ns5 file

### ISSUE THREAD

**Issue by ntolley** [BlackrockMicrosystems/NPMK#36]
I seem to be getting an error when attempting to open a .ns5 file the is related to timestamps:
![image](https://user-images.githubusercontent.com/55253912/116419397-04965600-a80b-11eb-8cb3-f2de58c56ce5.png)

I've run into the same problem with the python data loader with the following traceback:
![image](https://user-images.githubusercontent.com/55253912/116419591-34455e00-a80b-11eb-8228-09fe5f2031ba.png)

I'm unsure if this is a problem with my specific file, or a general bug with the .ns5 format.

**Comment by ntolley** [comment]
It seems that this is a problem with the newer release(s) of NPMK. I was successfully able to load different .ns5 files with the 4.5.3.0 release.

**Comment by kianabc** [comment]
Thanks Nick. I'll resolve this soon.

**Comment by kianabc** [comment]
If it's with the latest release of NPMK, why does it also show up on Python? Also, can you share a data file that causes this with me?

**Comment by kianabc** [comment]
I cannot replicate this issue. I'd need more information. Please share your data file and also tell me what version of MATLAB you're running. Thanks.

**Comment by kianabc** [comment]
Also, please send me your openNSx file too. My reference to timeStampBytes is on line 593 not 590. Did you try the latest version of NPMK (latest openNSx 7.4.1.0 released on April 20, 2021)?

Kian

**Comment by ntolley** [comment]
Sure thing! I'll send along the files shortly. This is on MATLAB 2019b but I'll try a different version.

Also I just tested the code on the latest version and ran into the same issue (the error is on line 593 as suggested).

**Comment by kianabc** [comment]
OK. I'm downloading the file. It should be done by late June. =D

**Comment by kianabc** [comment]
Hi Nick,

I fixed this, but it looks like you're recording using a very old (like 15+ years) file spec 2.1. Is there a reason for this? You should use FileSpec 2.3 (the latest).  Also, I recommend splitting your files into smaller chunks. 9 GB is huge and it will slow down your loading. You can have Central split into smaller chunks, or you can manually do that. If your computer has 16+ GB of RAM then this may not matter as much.

I'll upload a fix shortly. 

Kian

**Comment by kianabc** [comment]
Please email support@blackrockmicro.com to learn more about different File Specs.
